import { Arena } from "@/prisma/generated";
import { ArenaRepository } from "../../domain/repositories/ArenaRepository";
import { CreateArenaDto } from "./dto/CreateArenaDto";

export class CreateArenaUsecase {
    private arenaRepository: ArenaRepository;

    constructor(arenaRepository: ArenaRepository) {
        this.arenaRepository = arenaRepository;
    }

    async execute(createArenaDto: CreateArenaDto): Promise<Arena> {
        const arena: Arena = {
            id: -1, // ignore it, id will be auto-generated by prisma
            creatorId: createArenaDto.creatorId,
            challengerId: null,
            title: createArenaDto.title,
            description: createArenaDto.description,
            status: 1,
            startDate: createArenaDto.startDate,
        };

        const newArena = await this.arenaRepository.save(arena);
        return newArena;
    }
}
